baseURL = "https://ladarrellper.github.io/"
languageCode = "en-us"
title = "Paritosh Baghel"
theme = "nama-tema-anda"  # Gantilah dengan nama folder tema Anda
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
disableHugoGeneratorInject = true
pluralizeListTitles = false
pygmentsCodeFences = false
pygmentsUseClasses = false
minify = false
paginate = 9999

disableKinds = ["section", "categories", "tags"]

[permalinks]
  [[permalinks.writing]]
  path = "/:year/:month/:day/:slug/"

[params]
  description = "Paritosh Blog"

[frontmatter]
  author = "Paritosh Baghel"
  github = "https://github.com/paritoshmmmec"
  og_image = ""
  sitename = "Paritosh Blog"
  twitter = "@paritosh_pi"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "atom"
  [outputFormats.JSON]
    mediatype = "application/json"
    baseName = "feed"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
